# Generated by Django 4.1 on 2022-08-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_addsubscriber_movie_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addsubscriber",
            name="movie_one",
            field=models.BooleanField(null=True),
        ),
    ]
