# Generated by Django 4.1 on 2022-08-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_addsubscriber_movie_one"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addsubscriber",
            name="movie_one",
            field=models.BooleanField(default="No", null=True),
        ),
    ]
