# Generated by Django 4.1 on 2022-08-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_addsubscriber_movie_one"),
    ]

    operations = [
        migrations.AddField(
            model_name="addsubscriber",
            name="movie_two",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
