# Generated by Django 4.1 on 2022-08-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_movieone_subscribers_delete_addsubscriber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieone",
            old_name="movie_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="movieone",
            old_name="movie_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="movieone",
            old_name="movie_status",
            new_name="reservation",
        ),
        migrations.RenameField(
            model_name="subscribers",
            old_name="birth_day",
            new_name="birthday",
        ),
    ]
