# Generated by Django 4.1 on 2022-08-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_rename_movie_date_movieone_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribers",
            new_name="Subscriber",
        ),
    ]
