# Generated by Django 4.1 on 2022-08-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_rename_subscribers_subscriber"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MovieOne",
            new_name="Movie",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="subscriber",
            new_name="watcher",
        ),
    ]
