# Generated by Django 4.1 on 2022-08-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0011_remove_movie_watcher_subscriber_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="reservation",
        ),
        migrations.RemoveField(
            model_name="subscriber",
            name="movie",
        ),
        migrations.AddField(
            model_name="movie",
            name="watcher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.subscriber",
            ),
        ),
    ]
