# Generated by Django 4.1 on 2022-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0012_remove_movie_reservation_remove_subscriber_movie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="watcher",
        ),
        migrations.AddField(
            model_name="movie",
            name="watcher",
            field=models.ManyToManyField(to="book.subscriber"),
        ),
    ]
