# Generated by Django 4.1 on 2022-08-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0014_remove_movie_watcher_movie_watcher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
