# Generated by Django 4.1 on 2022-08-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0015_alter_subscriber_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
