# Generated by Django 4.1 on 2022-08-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0016_alter_subscriber_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="day",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
