# Generated by Django 4.1 on 2022-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0017_movie_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="date",
        ),
        migrations.AddField(
            model_name="movie",
            name="time",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
