# Generated by Django 4.1 on 2022-08-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0018_remove_movie_date_movie_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ticket",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
