# Generated by Django 4.1 on 2022-08-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0019_movie_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="day",
        ),
    ]
